brew install angular-cli
brew install ant
brew install awscli
brew install bash
brew install bash-completion
brew install bat
brew install berkeley-db
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install cask
brew install cffi
brew install coreutils
brew install curl
brew install diff-so-fancy
brew install docker
brew install docutils
brew install dos2unix
brew install editorconfig
brew install emacs
brew install figlet
brew install fontconfig
brew install freetype
brew install gdbm
brew install gettext
brew install giflib
brew install git
brew install git-lfs
brew install glib
brew install gmp
brew install gnupg
brew install gnutls
brew install go
brew install gradle
brew install graphite2
brew install grep
brew install groovy
brew install harfbuzz
brew install helm
brew install icu4c
brew install jansson
brew install jpeg-turbo
brew install jq
brew install kubectx
brew install kubernetes-cli
brew install libassuan
brew install libevent
brew install libgcrypt
brew install libgpg-error
brew install libidn2
brew install libksba
brew install liblinear
brew install libnghttp2
brew install libpng
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libunistring
brew install libusb
brew install libuv
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxrender
brew install libyaml
brew install little-cms2
brew install lua
brew install lz4
brew install lzo
brew install maven
brew install mpdecimal
brew install ncurses
brew install nettle
brew install nmap
brew install node
brew install npth
brew install oci-cli
brew install oniguruma
brew install openjdk
brew install openjdk@11
brew install openjdk@17
brew install openldap
brew install openssl@1.1
brew install openssl@3
brew install p11-kit
brew install pcre
brew install pcre2
brew install perl
brew install pinentry
brew install pixman
brew install pycparser
brew install python@3.10
brew install python@3.11
brew install pyyaml
brew install readline
brew install restic
brew install rtmpdump
brew install ruby
brew install screen
brew install six
brew install sqlite
brew install telnet
brew install terraform
brew install thefuck
brew install tmux
brew install tree
brew install unbound
brew install utf8proc
brew install vim
brew install webp
brew install wget
brew install xorgproto
brew install xz
brew install yq
brew install z
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
brew install zstd
brew install 1password
brew install adobe-acrobat-reader
brew install alfred
brew install bitwarden
brew install brave-browser
brew install dbeaver-community
brew install dropbox
brew install firefox
brew install fork
brew install github
brew install google-chrome
brew install google-cloud-sdk
brew install gpg-suite
brew install hiddenbar
brew install iterm2
brew install keepingyouawake
brew install microsoft-teams
brew install mqtt-explorer
brew install openvpn-connect
brew install postman
brew install raycast
brew install rectangle
brew install skype
brew install slack
brew install sonos
brew install sqlcl
brew install stretchly
brew install sublime-text
brew install swiftbar
brew install temurin
brew install temurin11
brew install temurin17
brew install temurin8
brew install transmit
brew install visual-studio-code
brew install vlc
brew install whatsapp
brew install yubico-yubikey-manager
