brew install ack
brew install android-sdk
brew install ant
brew install archey
brew install aspcud
brew install autoconf
brew install automake
brew install bash
brew install bash-completion
brew install boost
brew install brew-cask-completion
brew install camlp4
brew install cask-repair
brew install ccat
brew install clasp
brew install cloog
brew install cmake
brew install coreutils
brew install cscope
brew install diff-so-fancy
brew install dirmngr
brew install dnsmasq
brew install docker
brew install docker-machine
brew install docker-machine-driver-xhyve
brew install dos2unix
brew install doxygen
brew install editorconfig
brew install findutils
brew install freetype
brew install gdbm
brew install gettext
brew install git
brew install git-lfs
brew install gmp
brew install gmp@4
brew install gnupg2
brew install go
brew install gofabric8
brew install gpg-agent
brew install gradle
brew install grep
brew install gringo
brew install groovy
brew install highlight
brew install hr
brew install hub
brew install hugo
brew install icu4c
brew install isl
brew install isl@0.12
brew install itermocil
brew install jhead
brew install jpeg
brew install jq
brew install kubernetes-cli
brew install libassuan
brew install libev
brew install libevent
brew install libgcrypt
brew install libgpg-error
brew install libidn
brew install libksba
brew install libmpc
brew install libpng
brew install libsass
brew install libtool
brew install libusb
brew install libusb-compat
brew install libxml2
brew install libyaml
brew install lua
brew install mackup
brew install mas
brew install maven
brew install md5sha1sum
brew install moreutils
brew install mpfr
brew install nmap
brew install nvm
brew install ocaml
brew install ocamlbuild
brew install oniguruma
brew install opam
brew install openshift-cli
brew install openssh
brew install openssl
brew install pcre
brew install perl
brew install pinentry
brew install pkg-config
brew install pth
brew install python
brew install readline
brew install ruby
brew install screen
brew install sloccount
brew install socat
brew install springboot
brew install sqlite
brew install sudolikeaboss
brew install tidy-html5
brew install tmux
brew install unixodbc
brew install utf8proc
brew install vim
brew install wget
brew install xhyve
brew install xz
brew install z
brew install zlib
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
