brew install --cask 1password
brew install --cask adobe-acrobat-reader
brew install --cask alfred
brew install --cask bitwarden
brew install --cask brave-browser
brew install --cask dbeaver-community
brew install --cask dropbox
brew install --cask firefox
brew install --cask fork
brew install --cask github
brew install --cask google-chrome
brew install --cask google-cloud-sdk
brew install --cask gpg-suite
brew install --cask hiddenbar
brew install --cask iterm2
brew install --cask keepingyouawake
brew install --cask microsoft-teams
brew install --cask mqtt-explorer
brew install --cask openvpn-connect
brew install --cask postman
brew install --cask raycast
brew install --cask rectangle
brew install --cask skype
brew install --cask slack
brew install --cask sonos
brew install --cask sqlcl
brew install --cask stretchly
brew install --cask sublime-text
brew install --cask swiftbar
brew install --cask temurin
brew install --cask temurin11
brew install --cask temurin17
brew install --cask temurin8
brew install --cask transmit
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask whatsapp
brew install --cask yubico-yubikey-manager
