brew cask install 1password
brew cask install airfoil
brew cask install alfred
brew cask install atom
brew cask install avibrazil-rdm
brew cask install bartender
brew cask install betterzipql
brew cask install bitbar
brew cask install filezilla
brew cask install firefox
brew cask install flux
brew cask install franz
brew cask install garmin-express
brew cask install go2shell
brew cask install google-chrome
brew cask install hyperswitch
brew cask install istat-menus
brew cask install iterm2
brew cask install java
brew cask install keepassx
brew cask install launchcontrol
brew cask install mamp
brew cask install postman
brew cask install qlcolorcode
brew cask install slack
brew cask install soapui
brew cask install soundnode
brew cask install sourcetree
brew cask install spectacle
brew cask install spotify
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install vlc
