brew install abseil
brew install ack
brew install adns
brew install angular-cli
brew install ant
brew install aom
brew install apr
brew install apr-util
brew install argon2
brew install aspcud
brew install aspell
brew install atlassian-plugin-sdk
brew install autoconf
brew install automake
brew install awscli
brew install bash
brew install bash-completion
brew install bat
brew install bdw-gc
brew install berkeley-db
brew install boost
brew install brotli
brew install c-ares
brew install ca-certificates
brew install cairo
brew install cask
brew install ccat
brew install cffi
brew install clingo
brew install cloog
brew install cmake
brew install composer
brew install coreutils
brew install cscope
brew install curl
brew install curl-openssl
brew install diff-so-fancy
brew install dnsmasq
brew install docker
brew install docker-machine
brew install docutils
brew install dos2unix
brew install doxygen
brew install editorconfig
brew install emacs
brew install figlet
brew install findutils
brew install fontconfig
brew install freetds
brew install freetype
brew install fribidi
brew install fzf
brew install gd
brew install gdb
brew install gdbm
brew install gettext
brew install ghostscript
brew install giflib
brew install git
brew install git-lfs
brew install glib
brew install gmp
brew install gnupg
brew install gnupg2
brew install gnuplot
brew install gnutls
brew install go
brew install gobject-introspection
brew install gpatch
brew install gradle
brew install graphite2
brew install grep
brew install groff
brew install groovy
brew install guile
brew install harfbuzz
brew install helm
brew install helm@2
brew install highlight
brew install highway
brew install hr
brew install html2text
brew install httpd
brew install httpie
brew install hub
brew install hugo
brew install icu4c
brew install imath
brew install instantclient-basic
brew install isl
brew install isl@0.18
brew install jansson
brew install jasper
brew install jbig2dec
brew install jemalloc
brew install jhead
brew install jpeg
brew install jpeg-turbo
brew install jpeg-xl
brew install jq
brew install kns
brew install krb5
brew install kubectx
brew install kubernetes-cli
brew install ldns
brew install lftp
brew install libassuan
brew install libavif
brew install libcbor
brew install libcerf
brew install libev
brew install libevent
brew install libffi
brew install libfido2
brew install libgcrypt
brew install libgpg-error
brew install libiconv
brew install libidn
brew install libidn2
brew install libksba
brew install liblinear
brew install libmetalink
brew install libmpc
brew install libnet
brew install libnghttp2
brew install libpaper
brew install libpng
brew install libpq
brew install libpthread-stubs
brew install libsass
brew install libsodium
brew install libssh2
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libusb
brew install libusb-compat
brew install libuv
brew install libvmaf
brew install libx11
brew install libxau
brew install libxcb
brew install libxdmcp
brew install libxext
brew install libxml2
brew install libxrender
brew install libyaml
brew install libzip
brew install little-cms2
brew install logstash
brew install lua
brew install lua@5.3
brew install lz4
brew install lzo
brew install m-cli
brew install m4
brew install mackup
brew install mas
brew install maven
brew install mcrypt
brew install md5sha1sum
brew install mhash
brew install mongodb-community-shell
brew install mongodb-database-tools
brew install moreutils
brew install mpdecimal
brew install mpfr
brew install mysql
brew install n
brew install ncurses
brew install netpbm
brew install nettle
brew install nghttp2
brew install nmap
brew install node
brew install npth
brew install nvm
brew install ocaml
brew install ocamlbuild
brew install oci-cli
brew install oniguruma
brew install opam
brew install openexr
brew install openjdk
brew install openjdk@11
brew install openjdk@17
brew install openjdk@8
brew install openjpeg
brew install openldap
brew install openssh
brew install openssl@1.1
brew install openssl@3
brew install p11-kit
brew install pango
brew install pcre
brew install pcre2
brew install perl
brew install php
brew install pinentry
brew install pixman
brew install pkg-config
brew install postgresql@14
brew install prometheus
brew install protobuf
brew install protobuf@21
brew install psutils
brew install pth
brew install putty
brew install pycparser
brew install pygments
brew install python@3.10
brew install python@3.11
brew install python@3.8
brew install python@3.9
brew install pyyaml
brew install q
brew install qt@5
brew install readline
brew install renderizer
brew install restic
brew install rtmpdump
brew install ruby
brew install screen
brew install six
brew install sloccount
brew install socat
brew install sqlite
brew install sudolikeaboss
brew install tcl-tk
brew install tcptraceroute
brew install telnet
brew install terraform
brew install tfswitch
brew install thefuck
brew install tidy-html5
brew install tmux
brew install trash
brew install tree
brew install uchardet
brew install unbound
brew install unixodbc
brew install utf8proc
brew install vim
brew install webp
brew install wget
brew install xhyve
brew install xorgproto
brew install xz
brew install yarn
brew install yq
brew install z
brew install zlib
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
brew install zstd
brew install 1password
brew install 1password-cli
brew install adoptopenjdk11-openj9
brew install adoptopenjdk13
brew install adoptopenjdk13-openj9
brew install adoptopenjdk14
brew install adoptopenjdk8-openj9
brew install alfred
brew install android-sdk
brew install anydesk
brew install bartender
brew install betterzipql
brew install bitwarden
brew install brave-browser
brew install dbeaver-community
brew install discord
brew install docker
brew install firefox
brew install font-hack-nerd-font
brew install fork
brew install garmin-express
brew install gfxcardstatus
brew install github
brew install go2shell
brew install google-chrome
brew install google-cloud-sdk
brew install gpg-suite
brew install grammarly
brew install istat-menus
brew install iterm2
brew install keepingyouawake
brew install launchcontrol
brew install microsoft-auto-update
brew install microsoft-edge
brew install microsoft-teams
brew install mounty
brew install mqtt-explorer
brew install openvpn-connect
brew install postman
brew install rectangle
brew install robo-3t
brew install sequel-pro
brew install skype
brew install slack
brew install sourcetree
brew install sqlcl
brew install stretchly
brew install sublime-text
brew install telegram
brew install the-unarchiver
brew install transmit
brew install turbo-boost-switcher
brew install vagrant
brew install vagrant-manager
brew install visual-studio-code
brew install vlc
brew install whatsapp
brew install xbar
brew install yubico-yubikey-manager
