brew cask install 1password
brew cask install alfred
brew cask install android-sdk
brew cask install atom
brew cask install bartender
brew cask install betterzip
brew cask install bitbar
brew cask install firefox
brew cask install font-hack-nerd-font
brew cask install garmin-express
brew cask install gimp
brew cask install go2shell
brew cask install google-chrome
brew cask install google-cloud-sdk
brew cask install gpg-suite
brew cask install grammarly
brew cask install istat-menus
brew cask install iterm2-beta
brew cask install jumpshare
brew cask install keepingyouawake
brew cask install launchcontrol
brew cask install mamp
brew cask install oni
brew cask install osxfuse
brew cask install postman
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install sourcetree
brew cask install spectacle
brew cask install spotify
brew cask install sublime-text
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install transmit
brew cask install visual-studio-code
brew cask install vlc
brew cask install webpquicklook
brew cask install whatsapp
