brew cask install 1password
brew cask install airfoil
brew cask install airmail-beta
brew cask install alfred
brew cask install android-sdk
brew cask install atom
brew cask install avibrazil-rdm
brew cask install background-music
brew cask install bartender
brew cask install beardedspice
brew cask install betterzipql
brew cask install bitbar
brew cask install castbridge
brew cask install filezilla
brew cask install firefox
brew cask install flux
brew cask install fman
brew cask install font-hack-nerd-font
brew cask install franz
brew cask install garmin-express
brew cask install gimp
brew cask install go2shell
brew cask install google-chrome
brew cask install google-cloud-sdk
brew cask install google-play-music-desktop-player
brew cask install grammarly
brew cask install hyperswitch
brew cask install istat-menus
brew cask install iterm2
brew cask install iterm2-beta
brew cask install java
brew cask install jumpshare
brew cask install keepassx
brew cask install keepingyouawake
brew cask install launchcontrol
brew cask install mamp
brew cask install minishift
brew cask install moeditor
brew cask install near-lock
brew cask install nomad
brew cask install pgadmin4
brew cask install postman
brew cask install qlcolorcode
brew cask install sequel-pro
brew cask install shimo
brew cask install slack
brew cask install soapui
brew cask install soundcleod
brew cask install soundnode
brew cask install soundsource
brew cask install sourcetree
brew cask install spectacle
brew cask install spotify
brew cask install stay
brew cask install sublime-text
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install vagrant
brew cask install vagrant-manager
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install vlc
brew cask install vox
brew cask install whatsapp
