brew cask install 1password
brew cask install 1password-cli
brew cask install adoptopenjdk11-openj9
brew cask install adoptopenjdk13
brew cask install adoptopenjdk13-openj9
brew cask install adoptopenjdk14
brew cask install adoptopenjdk8-openj9
brew cask install alfred
brew cask install android-sdk
brew cask install atom
brew cask install bartender
brew cask install betterzipql
brew cask install bitbar
brew cask install brave-browser
brew cask install dbeaver-community
brew cask install firefox
brew cask install font-hack-nerd-font
brew cask install garmin-express
brew cask install gimp
brew cask install github
brew cask install go2shell
brew cask install google-chrome
brew cask install google-cloud-sdk
brew cask install gpg-suite
brew cask install grammarly
brew cask install istat-menus
brew cask install iterm2
brew cask install jumpshare
brew cask install keepingyouawake
brew cask install launchcontrol
brew cask install mamp
brew cask install microsoft-teams
brew cask install mounty
brew cask install osxfuse
brew cask install pgadmin4
brew cask install postman
brew cask install robo-3t
brew cask install sequel-pro
brew cask install skype
brew cask install slack
brew cask install soapui
brew cask install sourcetree
brew cask install spectacle
brew cask install spotify
brew cask install stay
brew cask install sublime-text
brew cask install teamviewer
brew cask install telegram
brew cask install the-unarchiver
brew cask install transmit
brew cask install vagrant
brew cask install vagrant-manager
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install vlc
brew cask install whatsapp
