brew cask install 1password
brew cask install 1password-cli
brew cask install adoptopenjdk11-openj9
brew cask install adoptopenjdk13
brew cask install adoptopenjdk13-openj9
brew cask install adoptopenjdk14
brew cask install adoptopenjdk8-openj9
brew cask install alfred
brew cask install android-sdk
brew cask install anydesk
brew cask install bartender
brew cask install betterzipql
brew cask install bitwarden
brew cask install brave-browser
brew cask install dbeaver-community
brew cask install discord
brew cask install docker
brew cask install firefox
brew cask install font-hack-nerd-font
brew cask install fork
brew cask install garmin-express
brew cask install gfxcardstatus
brew cask install github
brew cask install go2shell
brew cask install google-chrome
brew cask install google-cloud-sdk
brew cask install gpg-suite
brew cask install grammarly
brew cask install istat-menus
brew cask install iterm2
brew cask install keepingyouawake
brew cask install launchcontrol
brew cask install microsoft-auto-update
brew cask install microsoft-edge
brew cask install microsoft-teams
brew cask install mounty
brew cask install mqtt-explorer
brew cask install openvpn-connect
brew cask install postman
brew cask install rectangle
brew cask install robo-3t
brew cask install sequel-pro
brew cask install skype
brew cask install slack
brew cask install sourcetree
brew cask install sqlcl
brew cask install stretchly
brew cask install sublime-text
brew cask install telegram
brew cask install the-unarchiver
brew cask install transmit
brew cask install turbo-boost-switcher
brew cask install vagrant
brew cask install vagrant-manager
brew cask install visual-studio-code
brew cask install vlc
brew cask install whatsapp
brew cask install xbar
brew cask install yubico-yubikey-manager
