install archey
install bash
install bash-completion
install coreutils
install dnsmasq
install docker-machine
install findutils
install homebrew/dupes/grep
install highlight
install hugo
install tomanthony/brews/itermocil
install libidn
install libtool
install mackup
install moreutils
install node
install homebrew/dupes/openssh
install homebrew/php/php55-xdebug
install homebrew/dupes/screen
install wget
install z
install homebrew/dupes/zlib
install zsh
install zsh-syntax-highlighting
