brew install ack
brew install android-sdk
brew install ant
brew install archey
brew install atlassian/tap/atlassian-plugin-sdk
brew install bash
brew install bash-completion
brew install homebrew/completions/brew-cask-completion
brew install cloog
brew install coreutils
brew install cscope
brew install diff-so-fancy
brew install dnsmasq
brew install docker
brew install docker-machine
brew install dos2unix
brew install editorconfig
brew install findutils
brew install git
brew install git-lfs
brew install gradle
brew install homebrew/dupes/grep
brew install groovy
brew install highlight
brew install hugo
brew install tomanthony/brews/itermocil
brew install jq
brew install libidn
brew install libmpc
brew install libsass
brew install mackup
brew install maven
brew install moreutils
brew install nvm
brew install homebrew/dupes/openssh
brew install perl
brew install homebrew/php/php55-xdebug
brew install python
brew install ruby
brew install homebrew/dupes/screen
brew install sloccount
brew install pivotal/tap/springboot
brew install ravenac95/sudolikeaboss/sudolikeaboss
brew install tidy-html5
brew install vim
brew install wget
brew install xctool
brew install z
brew install homebrew/dupes/zlib
brew install zsh
brew install zsh-completions
brew install zsh-syntax-highlighting
