brew install Caskroom/cask/atom
brew install Caskroom/cask/betterzipql
brew install Caskroom/cask/bitbar
brew install Caskroom/cask/firefox
brew install Caskroom/cask/flux
brew install Caskroom/cask/garmin-express
brew install Caskroom/cask/go2shell
brew install Caskroom/cask/google-chrome
brew install Caskroom/cask/hyperswitch
brew install Caskroom/cask/istat-menus
brew install Caskroom/cask/launchcontrol
brew install Caskroom/cask/postman
brew install Caskroom/cask/qlcolorcode
brew install Caskroom/cask/slack
brew install Caskroom/cask/soapui
brew install Caskroom/cask/soundnode
brew install Caskroom/cask/sourcetree
brew install Caskroom/cask/sublime-text3
brew install Caskroom/cask/teamviewer
brew install Caskroom/cask/the-unarchiver
brew install Caskroom/cask/vlc
