#set -x

# Trace performance of zsh
zmodload zsh/zprof
# Then do: env ZSH_PROF= zsh -ic zprof
# This might help too:
# sudo rm -rf /private/var/log/asl/*.asl
# Also removing ~/.zcompdump* files might help


# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="agnoster"
ZSH_THEME="powerlevel9k/powerlevel9k"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# IMPORTANT: The zsh-syntax-highlighting MUST! be the last one
plugins=(docker osx brew gradle oc zsh-syntax-highlighting kubecontext)
#plugins=()

##############################################################################################
# User configuration
DISABLE_UPDATE_PROMPT=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir custom_kubens dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time battery os_icon)

POWERLEVEL9K_CUSTOM_KUBENS="kubectl_prompt"
POWERLEVEL9K_CUSTOM_KUBENS_BACKGROUND="blue"
POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="black"
POWERLEVEL9K_MODE='nerdfont-complete'
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
#POWERLEVEL9K_SHORTEN_DELIMITER=".."
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "

POWERLEVEL9K_BATTERY_CHARGING='yellow'
POWERLEVEL9K_BATTERY_CHARGED='green'
POWERLEVEL9K_BATTERY_DISCONNECTED='$DEFAULT_COLOR'
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
POWERLEVEL9K_BATTERY_LOW_COLOR='red'
POWERLEVEL9K_BATTERY_ICON='\uf1e6'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND="240"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="240"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="240"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="240"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uf017 %d-%m \uf073}"

export TERM="xterm-256color"

# This disables the robsonke@macbook prefix in prompts
DEFAULT_USER="robsonke"
. `brew --prefix`/etc/profile.d/z.sh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# gcloud completions
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

# zsh completions
fpath=(/usr/local/share/zsh-completions $fpath)

# load my aliases and functions
for file in ~/.{aliases,exports,functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

#################################

# give suggestions for missing utils
#if brew command command-not-found-init > /dev/null 2>&1; then eval "$(brew command-not-found-init)"; fi

# and maybe load some overrides from the custom folder
for file in ~/.dotfiles/custom/*; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

source $ZSH/oh-my-zsh.sh

# switch to java 8
setjdk 8

# You may need to manually set your language environment
export LANG=en_US.UTF-8

eval $(thefuck --alias)

# Use Git’s colored diff when available
hash git &>/dev/null;
if [ $? -eq 0 ]; then
  function diff() {
    git diff --no-index --color-words "$@";
  }
fi;

# Android sdk
#export ANDROID_HOME=/usr/local/opt/android-sdk

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="/usr/local/sbin:$PATH"
export PATH=/usr/local/php5/bin:$PATH

# sqlplus
export PATH=~/oracle/instantclient_12_2:$PATH


# initiate nice looking ls colors
eval `gdircolors ~/.dircolors`


#setopt extendedglob
#if [[ -n "${ZSH_COMPDUMP}"(#qN.mh+24) ]]; then
#  compinit -i -d "${ZSH_COMPDUMP}"
#  compdump
#else
#  compinit -C
#fi
